config/routes.rb
Rails.application.routes.draw do

  resources :notes do 
    collection do
      post :share_with_user
      get :all_notes
    end
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  authenticated :user do
    root 'notes#index', as: 'authenticated_root'
  end
  devise_scope :user do
    root 'devise/sessions#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  has_many :shared_notes, :dependent => :destroy

  validates :title, :description, presence: true
end

app/models/shared_note.rb
class SharedNote < ApplicationRecord
  belongs_to :user
  belongs_to :note
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook]
  has_many :notes
  has_many :shared_notes
  has_many :notes_shared_with_me, through: :shared_notes, source: :note

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.provider = auth.provider
      user.uid = auth.uid
      user.password = Devise.friendly_token[0,20]
    end
  end

  def apply_omniauth(auth)
    update_attributes(
      provider: auth.provider,
      uid: auth.uid
    )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, :can_access, only: [:show, :edit, :update, :destroy, :share_with_user]
  # GET /notes
  # GET /notes.json
  def index
    @notes = current_user.notes
    @shared_notes = current_user.notes_shared_with_me
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params.merge(user: current_user))

    respond_to do |format|
      if @note.save
        format.html { redirect_to notes_url, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to notes_url, notice: "Note #{@note.title} was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def all_notes
    if current_user.admin_role?
      @all_user = User.pluck(:email, :id)
      if params[:filter_user_id].present?
        @all_notes = Note.where(user_id: params[:filter_user_id])
      else
        @all_notes = Note.all
      end
      @user_selected = params[:filter_user_id]
    else
      redirect_to notes_url, notice: "You are not authorized to access this page"
    end
  end

  def share_with_user
    if params[:email].present?
      user = User.find_by_email params[:email]
      if user && @note.user!=user
        SharedNote.where(note: @note, user: user).first_or_create
        @error, @message = false, "Note was successfully shared with #{user.email}."
      else
        @error = true
        @message = @note.user==user ? "#{params[:email]} is the owner of this note" : 'User not found'
      end
      respond_to do |format|
        format.js { render file: '/notes/share_with_user.js', :content_type => 'text/javascript'}
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:title, :description)
    end

    def can_access
      unless current_user.admin_role? || current_user==@note.user || current_user.notes_shared_with_me.include?(@note)
         redirect_to notes_url, notice: "You are not authorized for this operation"
       end 
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def facebook
    if current_user.present?
      current_user.apply_omniauth(request.env["omniauth.auth"])
      redirect_to edit_user_registration_path, notice: "Facebook Account Linked!"
    else
      @user = User.from_omniauth(request.env["omniauth.auth"])
      sign_in_and_redirect @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css", :rel => "stylesheet"}/
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"}
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"}
    %script{:src => "https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"}
    %title NotesApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .header_home.row
      .title_resize
        = link_to 'Notes', root_path
      - if user_signed_in?
        %nav.navbar.bg-light.signup_component
          -if current_user.admin_role?
            = button_to 'Admin', all_notes_notes_path, method: :get, class: 'btn btn-outline-primary', style: "margin-right: 10px;"
          = button_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-danger', id: "logout_button"
      - else
        %nav.navbar.bg-light.signup_component
          = button_to 'Sign Up', new_user_registration_path, method: :get, class: 'btn btn-outline-primary', style: "margin-right: 10px;"
          = button_to 'Sign In', new_user_session_path, method: :get, class: 'btn btn-outline-secondary'
    %br
    - if notice  
      %p.notice.alert.alert-success= notice
    -if alert
      %p.alert.alert-danger= alert
    %main{:class => "#{controller.controller_name}"}
      = yield

app/views/notes/_form.html.haml
.input_field_small
  = form_for @note do |f|
    - if @note.errors.any?
      #error_explanation
        %h2= "#{pluralize(@note.errors.count, "error")} prohibited this note from being saved:"
        %ul
          - @note.errors.full_messages.each do |message|
            %li= message

    .field.form-group
      = f.label :title
      = f.text_field :title, :class => "form-control"
    .field.form-group
      = f.label :description
      = f.text_area :description, :class => "form-control update_note_text_area"
    .actions
      = f.submit 'Save',:class => "btn btn-success"

app/views/notes/_note.html.haml
-if notes.length > 0
  %ul.list-group{style: "overflow-x: auto"}
    %li
      %table.table.table-striped.table-bordered{style: "width: -webkit-fill-available;overflow-wrap: break-word;"}
        %thead
          %tr.d-flex
            %th.col-3 Title
            %th.col-4 Description
            %th.col-2 Owner
            %th.col-3{colspan: 3} Actions

        %tbody
          - notes.each do |note|
            %tr.d-flex
              %td.col-3= note.title
              %td.col-4= note.description
              %td.col-2= note.user.email
              %td.col-3
                = link_to 'Update', edit_note_path(note), class: "btn btn-primary"
                -if show_share
                  = link_to 'Delete', note, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"
                
                  %button.btn.btn-warning{"data-target": "#invite-modal-#{note.id}", 'data-toggle':'modal'} Share
                  .modal.fade{id: "invite-modal-#{note.id}",role: 'dialog'}
                    .modal-dialog
                      .modal-content
                        .modal-header
                          %h5.text-muted= "Share Note #{note.title}"
                          %button.close{"aria-label": "Close", "data-dismiss": "modal", type: "button"}
                            %span{"aria-hidden": "true"} &times;
                        .modal-body.text-center
                          = form_tag(share_with_user_notes_path,:remote => true) do
                            .container
                              #display_error.hidden{:class => "error_#{note.id}"}
                              .field.form-group.input_field_small
                                = label_tag :email, 'User Email:'
                                = text_field_tag :email, params[:email], :class => "form-control"
                              = hidden_field_tag :id, note.id
                              .actions
                                = submit_tag "share", :class => "btn btn-success", :value => "Share"
-else
  There are no notes

app/views/notes/all_notes.html.haml
%head
  = stylesheet_link_tag 'notes', media: 'all', |
      'data-turbolinks-track': 'reload'

%ul.nav.nav-tabs{:role => "tablist"}
  %li.nav-item
    %a.nav-link{"data-toggle" => "tab", :href => "#all_notes"}= "All Notes (#{@all_notes.length})"

%br

.tab-content
  #all_notes.tab-pane.active{style: "max-width: inherit;"}
    = form_tag(all_notes_notes_path, method: :get) do
      .container{style: "display: flex; margin-left: 0"}
        .field.form-group.input_field_small
          = select_tag :filter_user_id,options_for_select(@all_user, @user_selected),prompt: 'Select User'  ,class: 'form-control'
        .actions
          = submit_tag "Filter", :class => "btn btn-success", :value => "Filter"
    = render partial: '/notes/note', locals:{notes: @all_notes, show_share: true}

= link_to 'Create New Note', new_note_path, class: "btn btn-primary"

app/views/notes/edit.html.haml
%h1 Update Note

= render 'form'

= link_to 'Back', :back, :class => "btn btn-secondary"

app/views/notes/index.html.haml
%head
  = stylesheet_link_tag 'notes', media: 'all', |
      'data-turbolinks-track': 'reload'

%ul.nav.nav-tabs{:role => "tablist"}
  %li.nav-item
    %a.nav-link.active{"data-toggle" => "tab", :href => "#my_notes"}= "My Notes (#{@notes.length})"
  %li.nav-item
    %a.nav-link{"data-toggle" => "tab", :href => "#contributor_notes"}= "Shared With Me (#{@shared_notes.length})"

%br

.tab-content
  #my_notes.tab-pane.active{style: "max-width: inherit;"}
    = render partial: '/notes/note', locals:{notes: @notes, show_share: true}

  #contributor_notes.tab-pane.fade{style: "max-width: inherit;"}
    = render partial: '/notes/note', locals:{notes: @shared_notes, show_share: false}


= link_to 'Create New Note', new_note_path, class: "btn btn-primary"

app/views/notes/new.html.haml
%h1 New note

= render 'form'

= link_to 'Back', :back, :class => "btn btn-secondary"

app/views/notes/share_with_user.js.haml
$(".notice").remove();
$("#display_error").removeClass("hidden");
$(".error_#{@note.id}").append("<div class='notice'> #{@message}");
- if @error 
  $(".error_#{@note.id}").css("color","red");
- else
  $(".error_#{@note.id}").css("color","green");
  $("#email").val('');
$("#email").focus();

app/views/notes/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @note.title
%p
  %b Description:
  = @note.description
%p
  %b User:
  = @note.user.email

= link_to 'Edit', edit_note_path(@note), :class => "btn btn-primary"
= link_to 'Back', notes_path, :class => "btn btn-secondary"